{% set name = "genofig" %}
{% set version = "1.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://forgemia.inra.fr/public-pgba/genofig/-/archive/{{ version }}/genofig-{{ version }}.tar.gz"
  sha256: 6c1f265c19d69063d250738a1a88b13063282a5e5404b1ab09e7f9bf401ff57d

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
  run_exports:
    - {{ pin_subpackage("genofig", max_pin="x.x") }}    

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - biopython
    - gtk3
    - matplotlib-base
    - pycairo
    - cairosvg
    - pygobject
    - adwaita-icon-theme
    - blast

test:
  commands:
    - Genofig.py --version

about:
  home: https://forgemia.inra.fr/public-pgba/genofig
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "GUI-based application for the vizualisation and comparison of annotated genetic regions"
  doc_url: https://forgemia.inra.fr/public-pgba/genofig/-/blob/main/README.md

extra:
  recipe-maintainers:
    - Sebdu132

