{% set name = "GenoFig" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://forgemia.inra.fr/public-pgba/genofig/-/archive/1.0.3/genofig-1.0.3.tar.gz"
  sha256: 60cefdb09d7add66b82b1b96a1856127bb7f334474504430ac0897c6e27a34c0

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - biopython
    - gtk3
    - matplotlib
    - pycairo
    - cairosvg
    - pygobject
    - adwaita-icon-theme
    - blast

about:
  home: "https://forgemia.inra.fr/public-pgba/genofig"
  license: GPL3
  license_file: LICENSE
  summary: "GenoFig: tool for graphical vizualisation of annotated genetic regions, and homologous regions comparison"
  doc_url: "https://forgemia.inra.fr/public-pgba/genofig/-/blob/main/README.md"

extra:
  recipe-maintainers:
    - Sebastien Leclercq

